// <auto-generated />
using HypixelAPI.DTOs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RepoAPI.Data;

#nullable disable

namespace RepoAPI.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250824011645_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RepoAPI.Features.Items.Models.SkyblockItem", b =>
                {
                    b.Property<string>("ItemId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<ItemResponse>("Data")
                        .HasColumnType("jsonb");

                    b.Property<double>("NpcSellPrice")
                        .HasColumnType("double precision");

                    b.HasKey("ItemId");

                    b.ToTable("SkyblockItems");
                });
#pragma warning restore 612, 618
        }
    }
}
