// <auto-generated />
using System;
using HypixelAPI.DTOs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RepoAPI.Data;
using RepoAPI.Features.Wiki.Templates.ItemTemplate;
using RepoAPI.Features.Wiki.Templates.PetTemplate;

#nullable disable

namespace RepoAPI.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250827034904_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RepoAPI.Features.Items.Models.SkyblockItem", b =>
                {
                    b.Property<string>("InternalId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<ItemResponse>("Data")
                        .HasColumnType("jsonb");

                    b.Property<double>("NpcValue")
                        .HasColumnType("double precision");

                    b.Property<string>("RawTemplate")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<ItemTemplateDto>("TemplateData")
                        .HasColumnType("jsonb");

                    b.HasKey("InternalId");

                    b.ToTable("SkyblockItems");
                });

            modelBuilder.Entity("RepoAPI.Features.Items.Models.SkyblockItemRecipeLink", b =>
                {
                    b.Property<string>("InternalId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RecipeId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("InternalId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("SkyblockItemRecipeLinks");
                });

            modelBuilder.Entity("RepoAPI.Features.Pets.Models.SkyblockPet", b =>
                {
                    b.Property<string>("InternalId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("RawTemplate")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<PetTemplateDto>("TemplateData")
                        .HasColumnType("jsonb");

                    b.HasKey("InternalId");

                    b.ToTable("SkyblockPets");
                });

            modelBuilder.Entity("RepoAPI.Features.Recipes.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecipeId")
                        .HasMaxLength(512)
                        .HasColumnType("uuid");

                    b.Property<string>("Slot")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("RepoAPI.Features.Recipes.Models.SkyblockRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ResultInternalId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("ResultQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("ResultInternalId");

                    b.HasIndex("Type");

                    b.ToTable("SkyblockRecipes");
                });

            modelBuilder.Entity("RepoAPI.Features.Items.Models.SkyblockItem", b =>
                {
                    b.OwnsOne("RepoAPI.Features.Items.Models.ItemFlags", "Flags", b1 =>
                        {
                            b1.Property<string>("SkyblockItemInternalId")
                                .HasColumnType("character varying(512)");

                            b1.Property<bool>("Auctionable")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Bazaarable")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Enchantable")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Museumable")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Reforgeable")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Soulboundable")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Tradable")
                                .HasColumnType("boolean");

                            b1.HasKey("SkyblockItemInternalId");

                            b1.ToTable("SkyblockItems");

                            b1.WithOwner()
                                .HasForeignKey("SkyblockItemInternalId");
                        });

                    b.Navigation("Flags")
                        .IsRequired();
                });

            modelBuilder.Entity("RepoAPI.Features.Items.Models.SkyblockItemRecipeLink", b =>
                {
                    b.HasOne("RepoAPI.Features.Items.Models.SkyblockItem", null)
                        .WithMany()
                        .HasForeignKey("InternalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoAPI.Features.Recipes.Models.RecipeIngredient", b =>
                {
                    b.HasOne("RepoAPI.Features.Recipes.Models.SkyblockRecipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoAPI.Features.Recipes.Models.SkyblockRecipe", b =>
                {
                    b.HasOne("RepoAPI.Features.Items.Models.SkyblockItem", null)
                        .WithMany("Recipes")
                        .HasForeignKey("ResultInternalId");
                });

            modelBuilder.Entity("RepoAPI.Features.Items.Models.SkyblockItem", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("RepoAPI.Features.Recipes.Models.SkyblockRecipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
